name: dinhistory
description: Offline-first faith and history learning app.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  drift: ^2.15.0
  drift_flutter: ^0.2.0
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.20
  url_strategy: ^0.2.0
  flutter_markdown: ^0.6.18
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  drift_dev: ^2.15.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/content/en/cards/lesson_cards.json
    - assets/content/tr/cards/lesson_cards.json
    - assets/content/en/book/
    - assets/content/tr/book/
